### ISSUE TITLE
Exception while parsing a current Codeforces contest

### ISSUE THREAD

**Issue by Pastafarianist** [EgorKulikov/idea-chelper#34]
```
com.intellij.psi.JavaPsiFacade.findClass(Ljava/lang/String;)Lcom/intellij/psi/PsiClass;
java.lang.NoSuchMethodError: com.intellij.psi.JavaPsiFacade.findClass(Ljava/lang/String;)Lcom/intellij/psi/PsiClass;
    at net.egork.chelper.actions.ParseContestAction.actionPerformed(ParseContestAction.java:26)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
    at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:162)
    at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:126)
    at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:303)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I am using `dev-util/idea-community-14.1.5.141.2735.5` on Gentoo with `CHelper 3.0 beta 13` (from [here](https://code.google.com/p/idea-chelper/downloads/detail?name=chelper3.0beta13.jar&can=2&q=)). I've just installed the plugin and I'm not sure if I'm using it correctly. Here is my config file:

```
inputClass = java.util.Scanner
outputClass = java.io.PrintWriter
excludePackages = java.,javax.,com.sun.
outputDirectory = src
author = 
archiveDirectory = archive/unsorted
defaultDirectory = src/com/contests/codeforces
topcoderDirectory = src
testDirectory = src/com/contests/codeforces/tests
enableUnitTests = true
```

I have created a fresh project with the base package name `com.contests` using the standard IDEA template. Here is the current structure:

![image](https://cloud.githubusercontent.com/assets/1315874/11021770/8bb5bf3e-865d-11e5-99e2-21a7829f3214.png)

`Main.java` is nothing but an empty template with a `main` method.

Have I configured something wrong, or is this actually a bug?

**Comment by joney000** [comment]
@Pastafarianist @EgorKulikov I want to solve it , can you please assigned it to me ?
