### ISSUE TITLE
Test case location doesn't match

### ISSUE THREAD

**Issue by ntviet18** [EgorKulikov/idea-chelper#66]
Hi @EgorKulikov ,
When I create a new test case with name, e.g. `PokupkaBiletovTestCase`, it will be created with the same name and located at the task package, e.g. `com.example`. However, when I run the task it will complain 
```
Exception in thread "main" java.lang.ClassNotFoundException: PokupkaBiletovTestCase
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at net.egork.chelper.tester.NewTester.test(NewTester.java:58)
	at net.egork.chelper.tester.NewTester.main(NewTester.java:28)
```
I can fix this by adding the full qualified class name, e.g. `com.example.PokupkaBiletovTestCase` to the task specification.

But next time when I create a test with name `com.example.MarshrutTestCase`, it will create a file named `com.example.MarshrutTestCase.java` in package `com.example`. 

Do we have any other way to automatically configure it, rather than changing `testDirectory`?

**Comment by EgorKulikov** [comment]
It is interesting
Test directory had nothing to do with this, it is for unit test that are created automatically upon task archivation.
Is there any chance that you can record a screencast of what you are doing?

**Comment by ntviet18** [comment]
@EgorKulikov ,
Thank you for you quick reply. 
Please see the screencast [here](https://drive.google.com/open?id=1p9KOCWNWs0i4q7zCHtfN6ITZDc31hw0q)

**Comment by EgorKulikov** [comment]
I found the bug, it will be fixed in next beta

**Comment by ntviet18** [comment]
@EgorKulikov , thank you very much
